import assert from "node:assert/strict";
import test from "node:test";
import path from "node:path";
import { access, mkdir, readFile, rm, symlink, writeFile } from "node:fs/promises";

import { materializeSkill } from "../src/materialize";
import { createTempDir } from "./helpers/fixture";

test("materializeSkill wraps SKILL.md with the canonical name and preserves support files", async () => {
  const root = await createTempDir("skm-materialize-");
  const sourceDir = path.join(root, "source");
  const generatedDir = path.join(root, ".agents", "skills");
  await mkdir(sourceDir, { recursive: true });
  await writeFile(
    path.join(sourceDir, "SKILL.md"),
    [
      "---",
      "name: upstream-hello",
      "description: Upstream greeting skill",
      "---",
      "",
      "# Hello",
      "",
    ].join("\n"),
  );
  await writeFile(path.join(sourceDir, "notes.txt"), "notes\n");

  const outputDir = await materializeSkill({
    canonicalName: "review-code-quality",
    sourceDir,
    generatedSkillsDir: generatedDir,
    manifestSource: "https://example.com/example/skills/tree/main/skills/hello-skill",
    resolved: "abc123def456",
    strategy: "wrap",
  });

  const originalSkill = await readFile(path.join(sourceDir, "SKILL.md"), "utf8");
  const wrappedSkill = await readFile(path.join(outputDir, "SKILL.md"), "utf8");
  const copiedNote = await readFile(path.join(outputDir, "notes.txt"), "utf8");
  assert.match(originalSkill, /name: upstream-hello/);
  assert.doesNotMatch(originalSkill, /Generated by skm/);
  assert.match(wrappedSkill, /name: review-code-quality/);
  assert.doesNotMatch(wrappedSkill, /Generated by skm/);
  assert.equal(copiedNote, "notes\n");
  await assert.rejects(access(path.join(outputDir, ".skm-meta.json")));
});

test("materializeSkill rejects a symlinked SKILL.md in wrap mode before rewriting its target", async () => {
  const root = await createTempDir("skm-materialize-symlink-");
  const sourceDir = path.join(root, "source");
  const generatedDir = path.join(root, ".agents", "skills");
  const redirectedFile = path.join(root, "outside.md");
  await mkdir(sourceDir, { recursive: true });
  await writeFile(redirectedFile, "leave me alone\n");
  await symlink(path.relative(sourceDir, redirectedFile), path.join(sourceDir, "SKILL.md"));

  await assert.rejects(
    materializeSkill({
      canonicalName: "review-code-quality",
      sourceDir,
      generatedSkillsDir: generatedDir,
      manifestSource: "https://example.com/example/skills/tree/main/skills/hello-skill",
      resolved: "abc123def456",
      strategy: "wrap",
    }),
    /SKILL\.md.*symlink/i,
  );

  assert.equal(await readFile(redirectedFile, "utf8"), "leave me alone\n");
  await assert.rejects(access(path.join(generatedDir, "review-code-quality")));
  await rm(root, { recursive: true, force: true });
});

test("materializeSkill rejects a symlinked SKILL.md in link mode", async () => {
  const root = await createTempDir("skm-materialize-link-symlink-");
  const sourceDir = path.join(root, "source");
  const generatedDir = path.join(root, ".agents", "skills");
  const redirectedFile = path.join(root, "outside.md");
  await mkdir(sourceDir, { recursive: true });
  await writeFile(redirectedFile, "leave me alone\n");
  await symlink(path.relative(sourceDir, redirectedFile), path.join(sourceDir, "SKILL.md"));

  await assert.rejects(
    materializeSkill({
      canonicalName: "review-code-quality",
      sourceDir,
      generatedSkillsDir: generatedDir,
      manifestSource: "https://example.com/example/skills/tree/main/skills/hello-skill",
      resolved: "abc123def456",
      strategy: "link",
    }),
    /SKILL\.md.*symlink/i,
  );

  assert.equal(await readFile(redirectedFile, "utf8"), "leave me alone\n");
  await assert.rejects(access(path.join(generatedDir, "review-code-quality")));
  await rm(root, { recursive: true, force: true });
});
