import assert from "node:assert/strict";
import test from "node:test";
import path from "node:path";
import { access, mkdir, readFile, rm, symlink, writeFile } from "node:fs/promises";

import { materializeSkillResult } from "#src/materialize.js";
import { createTempDir } from "./helpers/fixture.js";

test("materializeSkill wraps SKILL.md with the canonical name and preserves support files", async () => {
  const root = await createTempDir("skm-materialize-");
  const sourceDir = path.join(root, "source");
  const generatedDir = path.join(root, ".agents", "skills");
  await mkdir(sourceDir, { recursive: true });
  await writeFile(
    path.join(sourceDir, "SKILL.md"),
    [
      "---",
      "name: upstream-hello",
      "description: Upstream greeting skill",
      "---",
      "",
      "# Hello",
      "",
    ].join("\n"),
  );
  await writeFile(path.join(sourceDir, "notes.txt"), "notes\n");

  const result = await materializeSkillResult({
    canonicalName: "review-code-quality",
    sourceDir,
    generatedSkillsDir: generatedDir,
    manifestSource: "https://example.com/example/skills/tree/main/skills/hello-skill",
    resolved: "abc123def456",
    strategy: "wrap",
  });
  assert.equal(result.isOk(), true);
  const outputDir = result._unsafeUnwrap();

  const originalSkill = await readFile(path.join(sourceDir, "SKILL.md"), "utf8");
  const wrappedSkill = await readFile(path.join(outputDir, "SKILL.md"), "utf8");
  const copiedNote = await readFile(path.join(outputDir, "notes.txt"), "utf8");
  assert.match(originalSkill, /name: upstream-hello/);
  assert.doesNotMatch(originalSkill, /Generated by skm/);
  assert.match(wrappedSkill, /name: review-code-quality/);
  assert.doesNotMatch(wrappedSkill, /Generated by skm/);
  assert.equal(copiedNote, "notes\n");
  await assert.rejects(access(path.join(outputDir, ".skm-meta.json")));
});

test("materializeSkillResult returns an err for a symlinked SKILL.md in wrap mode", async () => {
  const root = await createTempDir("skm-materialize-symlink-");
  const sourceDir = path.join(root, "source");
  const generatedDir = path.join(root, ".agents", "skills");
  const redirectedFile = path.join(root, "outside.md");
  await mkdir(sourceDir, { recursive: true });
  await writeFile(redirectedFile, "leave me alone\n");
  await symlink(path.relative(sourceDir, redirectedFile), path.join(sourceDir, "SKILL.md"));

  const result = await materializeSkillResult({
    canonicalName: "review-code-quality",
    sourceDir,
    generatedSkillsDir: generatedDir,
    manifestSource: "https://example.com/example/skills/tree/main/skills/hello-skill",
    resolved: "abc123def456",
    strategy: "wrap",
  });

  assert.equal(result.isErr(), true);
  assert.match(result._unsafeUnwrapErr().message, /SKILL\.md.*symlink/i);

  assert.equal(await readFile(redirectedFile, "utf8"), "leave me alone\n");
  await assert.rejects(access(path.join(generatedDir, "review-code-quality")));
  await rm(root, { recursive: true, force: true });
});

test("materializeSkillResult returns an err for a symlinked SKILL.md in link mode", async () => {
  const root = await createTempDir("skm-materialize-link-symlink-");
  const sourceDir = path.join(root, "source");
  const generatedDir = path.join(root, ".agents", "skills");
  const redirectedFile = path.join(root, "outside.md");
  await mkdir(sourceDir, { recursive: true });
  await writeFile(redirectedFile, "leave me alone\n");
  await symlink(path.relative(sourceDir, redirectedFile), path.join(sourceDir, "SKILL.md"));

  const result = await materializeSkillResult({
    canonicalName: "review-code-quality",
    sourceDir,
    generatedSkillsDir: generatedDir,
    manifestSource: "https://example.com/example/skills/tree/main/skills/hello-skill",
    resolved: "abc123def456",
    strategy: "link",
  });

  assert.equal(result.isErr(), true);
  assert.match(result._unsafeUnwrapErr().message, /SKILL\.md.*symlink/i);

  assert.equal(await readFile(redirectedFile, "utf8"), "leave me alone\n");
  await assert.rejects(access(path.join(generatedDir, "review-code-quality")));
  await rm(root, { recursive: true, force: true });
});

test("materializeSkillResult returns an err for unsafe canonical names", async () => {
  const root = await createTempDir("skm-materialize-");
  const sourceDir = path.join(root, "source");
  const generatedDir = path.join(root, ".agents", "skills");
  await mkdir(sourceDir, { recursive: true });
  await writeFile(path.join(sourceDir, "SKILL.md"), "# Hello\n");

  const result = await materializeSkillResult({
    canonicalName: "../../escaped-skill",
    sourceDir,
    generatedSkillsDir: generatedDir,
    manifestSource: "https://example.com/example/skills/tree/main/skills/hello-skill",
    resolved: "abc123def456",
    strategy: "wrap",
  });

  assert.equal(result.isErr(), true);
  assert.match(result._unsafeUnwrapErr().message, /invalid canonical name/i);
  await assert.rejects(access(path.join(root, "escaped-skill")));
});

test("materializeSkillResult returns an err for control or windows-hostile canonical names", async () => {
  const root = await createTempDir("skm-materialize-");
  const sourceDir = path.join(root, "source");
  const generatedDir = path.join(root, ".agents", "skills");
  await mkdir(sourceDir, { recursive: true });
  await writeFile(path.join(sourceDir, "SKILL.md"), "# Hello\n");

  const windowsHostileResult = await materializeSkillResult({
    canonicalName: "bad:name",
    sourceDir,
    generatedSkillsDir: generatedDir,
    manifestSource: "https://example.com/example/skills/tree/main/skills/hello-skill",
    resolved: "abc123def456",
    strategy: "wrap",
  });
  assert.equal(windowsHostileResult.isErr(), true);
  assert.match(windowsHostileResult._unsafeUnwrapErr().message, /invalid canonical name/i);

  const controlCharacterResult = await materializeSkillResult({
    canonicalName: "bad\u0000name",
    sourceDir,
    generatedSkillsDir: generatedDir,
    manifestSource: "https://example.com/example/skills/tree/main/skills/hello-skill",
    resolved: "abc123def456",
    strategy: "wrap",
  });
  assert.equal(controlCharacterResult.isErr(), true);
  assert.match(controlCharacterResult._unsafeUnwrapErr().message, /invalid canonical name/i);
});
