import { readFile, symlink, writeFile } from "node:fs/promises";
import path from "node:path";

import { SkmError } from "./errors";
import { copyDirectory, ensureDir, pathExists, removeIfExists } from "./fs";
import { MaterializationStrategy } from "./manifest";

export interface MaterializeSkillOptions {
  canonicalName: string;
  sourceDir: string;
  generatedSkillsDir: string;
  manifestSource: string;
  resolved: string;
  strategy: MaterializationStrategy;
}

export async function materializeSkill(options: MaterializeSkillOptions): Promise<string> {
  const outputDir = path.join(options.generatedSkillsDir, options.canonicalName);
  await ensureDir(options.generatedSkillsDir);
  await removeIfExists(outputDir);

  if (options.strategy === "link") {
    await symlink(options.sourceDir, outputDir, process.platform === "win32" ? "junction" : "dir");
    return outputDir;
  }

  await copyDirectory(options.sourceDir, outputDir);

  if (options.strategy === "wrap") {
    const wrapped = await wrapSkillMarkdown(
      path.join(outputDir, "SKILL.md"),
      options.canonicalName,
      options.manifestSource,
      options.resolved,
    );
    await writeFile(path.join(outputDir, "SKILL.md"), wrapped);
  } else if (!(await pathExists(path.join(outputDir, "SKILL.md")))) {
    throw new SkmError(`Materialized skill at ${outputDir} is missing SKILL.md`, 4);
  }

  await writeFile(
    path.join(outputDir, ".skm-meta.json"),
    `${JSON.stringify(
      {
        source: options.manifestSource,
        resolved: options.resolved,
        strategy: options.strategy,
      },
      null,
      2,
    )}\n`,
  );

  return outputDir;
}

async function wrapSkillMarkdown(
  skillMdPath: string,
  canonicalName: string,
  manifestSource: string,
  resolved: string,
): Promise<string> {
  const raw = await readFile(skillMdPath, "utf8");
  const provenanceComment = `\n\n<!-- Generated by skm from ${manifestSource} @ ${resolved} -->\n`;

  if (!raw.startsWith("---\n")) {
    return [
      "---",
      `name: ${canonicalName}`,
      "description: Materialized by skm",
      "---",
      "",
      raw.trimEnd(),
      provenanceComment.trimEnd(),
      "",
    ].join("\n");
  }

  const endIndex = raw.indexOf("\n---", 4);
  if (endIndex === -1) {
    return `${raw.trimEnd()}${provenanceComment}`;
  }

  const frontmatter = raw.slice(4, endIndex).split("\n");
  const body = raw.slice(endIndex + 5).replace(/^\n/, "");
  let replacedName = false;
  const nextFrontmatter = frontmatter.map((line) => {
    if (line.startsWith("name:")) {
      replacedName = true;
      return `name: ${canonicalName}`;
    }
    return line;
  });
  if (!replacedName) {
    nextFrontmatter.unshift(`name: ${canonicalName}`);
  }

  return [
    "---",
    ...nextFrontmatter,
    "---",
    "",
    body.trimEnd(),
    provenanceComment.trimEnd(),
    "",
  ].join("\n");
}
